#!/usr/bin/env bash
#
# Normalize raw `gstatetests -v <dir>` output into a stable, diffable summary
# used as the regression baseline (.github/gstatetests-baseline.txt).
#
# Two kinds of lines are emitted:
#   <key>=<n>     aggregate counts (pass_root, pass_full, pass_core, fail, ...)
#   test=<id>     one per FAIL test — a NEW id here relative to the baseline
#                 (i.e. a test that used to pass) is a regression.
# INCON tests are intentionally not listed: they are expected, out-of-scope
# outcomes (typed transactions we don't execute, fuel/wall-timeouts), so only
# pass -> fail transitions count as id-level regressions. The aggregate counts
# still surface any pass -> incon drift.
#
# The output format is identical to statetests_summary.sh — the modern
# GeneralStateTests runner (`gstatetests`) prints the same
# `pass(root=… full+=… core+=…) fail=… incon=… crash=…` aggregate line and the
# same `FAIL <id>: …` / `INCON <id>: …` per-test notes.
#
# Usage: gstatetests_summary.sh <raw-output-file>
set -euo pipefail

raw="${1:?usage: gstatetests_summary.sh <raw-output-file>}"

# The final aggregate line, e.g.
#   pass(root=0 full+=387 core+=517) fail=2 incon=10 crash=0 (total 916)
total_line="$(grep -E 'pass\(root=[0-9]+ full\+=[0-9]+ core\+=[0-9]+\) fail=[0-9]+' "$raw" | tail -1 || true)"
if [ -z "$total_line" ]; then
  echo "gstatetests_summary.sh: no aggregate 'pass(root=… full+=… core+=…) fail=…' line" \
       "found in '$raw' — the run is incomplete or its output format changed." >&2
  exit 2
fi
num() { sed -nE "s/.*[ (]$1=([0-9]+).*/\1/p" <<<"$total_line"; }

echo "# gstatetests regression baseline (generated by gstatetests_summary.sh)"
echo "pass_root=$(num root)"
echo "pass_full=$(num 'full\+')"
echo "pass_core=$(num 'core\+')"
echo "fail=$(num fail)"
echo "incon=$(num incon)"
echo "crash=$(num crash)"
echo "total=$(sed -nE 's/.*total ([0-9]+).*/\1/p' <<<"$total_line")"

# Per-test notes look like:  "FAIL invalidTr_Cancun_d0g0v0: <msg>"
# Key on the identifier only (not the message), so reworded mismatch messages
# do not register as spurious regressions.
# `|| true`: a run with zero FAILs makes `grep` exit 1 — without this,
# `set -o pipefail` would fail the whole script after a valid summary.
{ grep -E '^FAIL ' "$raw" || true; } \
  | sed -E 's/^FAIL ([^:]+):.*/\1/' \
  | sort -u \
  | sed 's/^/test=/'
