#!/usr/bin/env bash
#
# Normalize raw `vmtests <dir>` output into a stable, diffable summary that is
# used as the regression baseline (.github/vmtests-baseline.txt).
#
# Two kinds of lines are emitted:
#   <key>=<n>     aggregate counts (pass, fail, crash, ...)
#   test=<id>     one per non-passing test (FAIL/CRASH) — a NEW id appearing
#                 here relative to the baseline is a regression.
# INCON/SKIP tests are intentionally not listed: they are expected, out-of-scope
# outcomes, so only pass -> fail/crash transitions count as regressions.
#
# Usage: vmtests_summary.sh <raw-output-file>
set -euo pipefail

raw="${1:?usage: vmtests_summary.sh <raw-output-file>}"

# The final aggregate line, e.g.
#   pass=491 fail=4 skip(unsup=6 keccak=23 gas=2) incon=28 crash=55 (total 609)
total_line="$(grep -E 'pass=[0-9]+ fail=[0-9]+' "$raw" | tail -1 || true)"
if [ -z "$total_line" ]; then
  echo "vmtests_summary.sh: no aggregate 'pass=… fail=…' line found in '$raw'" \
       "— the run is incomplete or its output format changed." >&2
  exit 2
fi
num() { sed -nE "s/.*(^|[ (])$1=([0-9]+).*/\2/p" <<<"$total_line"; }

echo "# vmtests regression baseline (generated by vmtests_summary.sh)"
echo "pass=$(num pass)"
echo "fail=$(num fail)"
echo "skip_unsup=$(num unsup)"
echo "skip_keccak=$(num keccak)"
echo "skip_gas=$(num gas)"
echo "incon=$(num incon)"
echo "crash=$(num crash)"
echo "total=$(sed -nE 's/.*total ([0-9]+).*/\1/p' <<<"$total_line")"

# Named FAIL/CRASH notes look like:  "    FAIL smod0: ..."  /  "    CRASH exp1.json: timeout"
# Key on the identifier only (not the message), so reworded messages or a
# CRASH<->FAIL category flip do not register as spurious regressions.
grep -E '^[[:space:]]+(FAIL|CRASH) ' "$raw" \
  | sed -E 's/^[[:space:]]+(FAIL|CRASH) ([^:]+):.*/\2/' \
  | sort -u \
  | sed 's/^/test=/'
