module

public import EvmSemantics.Crypto.Weierstrass

/-!
`EvmSemantics.Crypto.Bn254` — the alt_bn128 / BN254 curve constants
plus concrete `Fp := Fin p` / `Curve p` bindings.

BN254 is the short-Weierstrass curve `y² = x³ + 3` (mod `p`) — the
pairing-friendly curve Ethereum uses for the Byzantium-era zkSNARK
precompiles ECADD (0x06), ECMUL (0x07), and ECPAIRING (0x08). It is
generated by a single Barreto–Naehrig parameter `u`; every other
constant on this page is a low-degree polynomial in `u`.

Ties to the tower fields (`Fp2 → Fp6 → Fp12`, in their own modules):
each tower level pins its coefficients to `Fin Bn254.p`, so no
runtime modulus needs to be threaded through — the type carries it.
-/

@[expose] public section

namespace EvmSemantics.Crypto.Bn254

/-- The BN family parameter `u`. Every other BN254 constant is a
    polynomial in `u`, per Barreto–Naehrig (2005). BN254 uses
    `u = 4965661367192848881` (`≈ 2⁶²`), chosen so that both the
    field prime and the group order below are prime. -/
def u : Nat := 4965661367192848881

/-- BN254 base-field prime `p = 36u⁴ + 36u³ + 24u² + 6u + 1`
    (≈ 2²⁵⁴). Decimal value:
    `21888242871839275222246405745257275088696311157297823662689037894645226208583`. -/
def p : Nat := 36*u^4 + 36*u^3 + 24*u^2 + 6*u + 1

/-- BN254 group order `N = 36u⁴ + 36u³ + 18u² + 6u + 1` (the twist
    of `p` — differs only in the `u²` coefficient). Decimal value:
    `21888242871839275222246405745257275088548364400416034343698204186575808495617`. -/
def N : Nat := 36*u^4 + 36*u^3 + 18*u^2 + 6*u + 1

/-- `p` is nonzero — required for `Fin p`'s numeric-tower instances
    to resolve. The `+ 1` at the tail of the polynomial makes this
    trivial: `p ≥ 1`. -/
instance : NeZero p := ⟨by unfold p; omega⟩

/-- Generator `x`-coordinate. -/
def Gx : Nat := 1

/-- Generator `y`-coordinate. -/
def Gy : Nat := 2

/-- Field elements over `F_p`. Type-alias to `Fin p` so BN254
    coordinates are distinct from secp256k1's (accepting a raw
    `Nat` in place of an `Fp` here is a type error). -/
abbrev Fp := Fin p

/-- BN254 G₁ point over `Fp`. -/
abbrev Point := EvmSemantics.Crypto.EC.Point Fp

/-- The BN254 curve packaged for the generic point operations. -/
def curve : EvmSemantics.Crypto.Weierstrass.Curve p := { b := Fin.ofNat _ 3 }

/-- The BN254 generator point `G = (1, 2)`. -/
def G : Point := .affine (Fin.ofNat _ Gx) (Fin.ofNat _ Gy)

/-- Double a BN254 point. -/
@[inline] def doublePoint (P : Point) : Point :=
  EvmSemantics.Crypto.Weierstrass.doublePoint curve P

/-- Add two BN254 points. -/
@[inline] def addPoint (P Q : Point) : Point :=
  EvmSemantics.Crypto.Weierstrass.addPoint curve P Q

/-- Scalar multiplication on BN254. -/
@[inline] def scalarMul (k : Nat) (P : Point) : Point :=
  EvmSemantics.Crypto.Weierstrass.scalarMul curve k P

/-- Curve-membership check. -/
@[inline] def onCurve (x y : Fp) : Bool :=
  EvmSemantics.Crypto.Weierstrass.onCurve curve x y

end EvmSemantics.Crypto.Bn254
