module

public import EvmSemantics.Crypto.Weierstrass
public import EvmSemantics.Crypto.Fp2
public import EvmSemantics.Crypto.Fp6
public import EvmSemantics.Crypto.Fp12
public import EvmSemantics.Crypto.G2

/-!
`EvmSemantics.Crypto.Bls12381` — the BLS12-381 curve constants plus
concrete tower-type bindings.

BLS12-381 is a short-Weierstrass pairing-friendly curve
`y² = x³ + 4` (mod `p`) with embedding degree 12, used by Ethereum
for KZG point-evaluation (`0x0A`, Cancun, EIP-4844) and the
EIP-2537 precompile set (`0x0B..0x11`, Prague).

The whole BLS family is generated by a single Barreto–Lynn–Scott
parameter `u`; every other constant on this page is a low-degree
polynomial in `u`. BLS12-381 uses `u = -0xd201000000010000` (chosen
for low Hamming weight in the Miller loop counter).

Ties to the tower (`Fp2 → Fp6 → Fp12`, in `Fp2.lean` / `Fp6.lean` /
`Fp12.lean`): those modules are polymorphic in the modulus, and
this file supplies `[NeZero p]` and `[SexticNonResidue p]` so
BLS12-381 gets the operator sugar (`a * b`, `a⁻¹`, `a ^ n`) for
free. BLS12-381's sextic non-residue is `ξ = 1 + u ∈ Fp2` —
`mulByXi` is just `(a₀ − a₁) + (a₀ + a₁)·u`, i.e. two additions.
-/

@[expose] public section

namespace EvmSemantics.Crypto.Bls12381

/-- The BLS parameter `u = −0xd201000000010000` (a specific negative
    integer of Hamming weight 6 in NAF, chosen so that both `p` and
    the group order are prime). We store its absolute value here;
    the negative sign is applied in the Miller loop (which iterates
    over `|u|` in binary and inverts the accumulator for the
    negative-`u` half — see `Bls12381.Pairing`). -/
def absU : Nat := 0xd201000000010000

/-- BLS12-381 base-field prime. The Barreto–Lynn–Scott formula is
    `p = (u−1)² · (u⁴ − u² + 1)/3 + u` with `u` signed. Substituting
    `u = −absU` — even powers of `u` are even powers of `absU`, and
    `(u−1)² = (absU+1)²` — the `+u` at the end becomes `−absU`. Hex:
    `0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab`. -/
def p : Nat := (absU + 1)^2 * (absU^4 - absU^2 + 1) / 3 - absU

/-- BLS12-381 subgroup order (aka `r`). Formula `N = u⁴ − u² + 1`;
    since only even powers of `u` appear, `N = absU⁴ − absU² + 1`.
    Hex:
    `0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001`. -/
def N : Nat := absU^4 - absU^2 + 1

/-- `p` is nonzero — required for `Fin p`'s numeric-tower instances. -/
instance : NeZero p := ⟨by unfold p; decide⟩

/-- Field elements over `F_p`. -/
abbrev Fp := Fin p

/-- BLS12-381 `Fp2`. -/
abbrev Fp2 := _root_.Fp2 p

/-- BLS12-381 `Fp6`. -/
abbrev Fp6 := _root_.Fp6 p

/-- BLS12-381 `Fp12`. -/
abbrev Fp12 := _root_.Fp12 p

/-- BLS12-381 G₁ point over `Fp`. -/
abbrev Point := EvmSemantics.Crypto.EC.Point Fp

/-- G₁ generator `x`-coordinate. Hex:
    `0x17f1d3a73197d7942695638c4fa9ac0fc3688c4f9774b905a14e3a3f171bac586c55e83ff97a1aeffb3af00adb22c6bb`. -/
def Gx : Nat :=
  0x17f1d3a73197d7942695638c4fa9ac0fc3688c4f9774b905a14e3a3f171bac586c55e83ff97a1aeffb3af00adb22c6bb

/-- G₁ generator `y`-coordinate. Hex:
    `0x08b3f481e3aaa0f1a09e30ed741d8ae4fcf5e095d5d00af600db18cb2c04b3edd03cc744a2888ae40caa232946c5e7e1`. -/
def Gy : Nat :=
  0x08b3f481e3aaa0f1a09e30ed741d8ae4fcf5e095d5d00af600db18cb2c04b3edd03cc744a2888ae40caa232946c5e7e1

/-- The BLS12-381 G₁ curve packaged for the generic point operations
    (`y² = x³ + 4`, i.e. `a = 0`, `b = 4`). -/
def curve : EvmSemantics.Crypto.Weierstrass.Curve p := { a := 0, b := Fin.ofNat _ 4 }

/-- The BLS12-381 G₁ generator. -/
def G : Point := .affine (Fin.ofNat _ Gx) (Fin.ofNat _ Gy)

/-- Double a BLS12-381 G₁ point. -/
@[inline] def doublePoint (P : Point) : Point :=
  EvmSemantics.Crypto.Weierstrass.doublePoint curve P

/-- Add two BLS12-381 G₁ points. -/
@[inline] def addPoint (P Q : Point) : Point :=
  EvmSemantics.Crypto.Weierstrass.addPoint curve P Q

/-- Scalar multiplication on BLS12-381 G₁. -/
@[inline] def scalarMul (k : Nat) (P : Point) : Point :=
  EvmSemantics.Crypto.Weierstrass.scalarMul curve k P

/-- Curve-membership check on BLS12-381 G₁. -/
@[inline] def onCurve (x y : Fp) : Bool :=
  EvmSemantics.Crypto.Weierstrass.onCurve curve x y

/-- BLS12-381 G₂ point. -/
abbrev G2Point := EvmSemantics.Crypto.G2.Point p

/-- BLS12-381's G₂ twist coefficient `b' = 4·(1 + u) ∈ Fp2` (M-type
    twist). `4·(1 + u) = (4, 4)` as an Fp2 pair. -/
def g2TwistB : Fp2 := { c0 := Fin.ofNat _ 4, c1 := Fin.ofNat _ 4 }

/-- BLS12-381's G₂ curve packaged for the polymorphic `G2.*` ops. -/
def g2Curve : EvmSemantics.Crypto.G2.Curve p := { b := g2TwistB }

/-- G₂ generator `x` `c0`-coordinate. -/
def G2xC0 : Nat :=
  0x24aa2b2f08f0a91260805272dc51051c6e47ad4fa403b02b4510b647ae3d1770bac0326a805bbefd48056c8c121bdb8

/-- G₂ generator `x` `c1`-coordinate. -/
def G2xC1 : Nat :=
  0x13e02b6052719f607dacd3a088274f65596bd0d09920b61ab5da61bbdc7f5049334cf11213945d57e5ac7d055d042b7e

/-- G₂ generator `y` `c0`-coordinate. -/
def G2yC0 : Nat :=
  0xce5d527727d6e118cc9cdc6da2e351aadfd9baa8cbdd3a76d429a695160d12c923ac9cc3baca289e193548608b82801

/-- G₂ generator `y` `c1`-coordinate. -/
def G2yC1 : Nat :=
  0x606c4a02ea734cc32acd2b02bc28b99cb3e287e85a763af267492ab572e99ab3f370d275cec1da1aaa9075ff05f79be

/-- The BLS12-381 G₂ generator point. -/
def G2 : G2Point :=
  .affine
    { c0 := Fin.ofNat _ G2xC0, c1 := Fin.ofNat _ G2xC1 }
    { c0 := Fin.ofNat _ G2yC0, c1 := Fin.ofNat _ G2yC1 }

end EvmSemantics.Crypto.Bls12381

/-- BLS12-381's sextic non-residue is `ξ = 1 + u ∈ Fp2`. Multiplication
    by `ξ` has an especially fast specialised form — just two
    additions:
    `(a₀ + a₁·u) · (1 + u) = (a₀ − a₁) + (a₀ + a₁)·u`.
    Compared to BN254's `9 + u` this saves the two multiplications
    by 9 per Fp6 op. -/
@[inline] instance instBls12381SexticNonResidue :
    SexticNonResidue EvmSemantics.Crypto.Bls12381.p where
  mulByXi a := { c0 := a.c0 - a.c1, c1 := a.c0 + a.c1 }
